spring:
  datasource:
    hikari:
      maximum-pool-size: 50
  data:
    redis:
      lettuce:
        pool:
          max-active: 32
  rabbitmq:
    listener:
      simple:
        concurrency: 5

logging:
  level:
    root: WARN
  file:
    name: /var/log/seckill-mall/app.log
seckill:
  security:
    sign-secret: ${SECKILL_SIGN_SECRET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false
  production: true

jwt:

  access-token-expiration: 1800000
  refresh-token-expiration: 604800000